
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: parkcharge-mailhog
      ports:
        - "8001:8025"

    redis:
      image: redis:alpine
      container_name: parrkcharge-redis

    mysql:
      image: mysql:5.7.22
      container_name: parkcharge-mysql
      working_dir: /application
      restart: unless-stopped
      tty: true
      volumes:
        - .:/application
      environment:
        MYSQL_DATABASE: parkcharge
        MYSQL_ROOT_PASSWORD: root
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: parkcharge-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: parkcharge-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

